routes/web.php
<?php

use App\Http\Controllers\DiagnosisController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    // Dashboard
    Route::get('/', fn () => view('dashboard'))->name('dashboard');

    // Patients
    Route::resource('/patients', PatientController::class)->except('destroy');
    Route::group([
        'prefix' => '/patients/{patient}',
        'as' => 'patients.',
    ], function () {
        // Diagnoses
        Route::resource('/diagnoses', DiagnosisController::class)->except('destroy');
    });

    Route::middleware('isAdmin')->group(function () {
        // Users
        Route::resource('/users', UserController::class)->except('destroy');
    });
});

app/Models/Diagnosis.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;
use Wildside\Userstamps\Userstamps;

class Diagnosis extends Model
{
    use HasFactory, LogsActivity, SoftDeletes, Userstamps;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'date',
        'description',
        'patient_id',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'date' => 'datetime',
        'description' => 'encrypted',
    ];

    /**
     * Scope a query to only include diagnoses by end date.
     *
     * @param \Illuminate\Database\Eloquent\Builder  $query
     * @param string  $search
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeEndDate(Builder $query, $search)
    {
        $search = ('/' == substr($search, 2, 1)) ? Carbon::parse('d/m/Y', $search) : $search;
        return $query->whereDate('date', '<=', $search);
    }

    /**
     * Scope a query to only include diagnoses by patient.
     *
     * @param \Illuminate\Database\Eloquent\Builder  $query
     * @param int|array  $patient_id
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePatient(Builder $query, $patient_id)
    {
        return $query->whereIn('patient_id', is_array($patient_id) ? $patient_id : explode(',', $patient_id));
    }

    /**
     * Scope a query to only include diagnoses by start date.
     *
     * @param \Illuminate\Database\Eloquent\Builder  $query
     * @param string  $search
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeStartDate(Builder $query, $search)
    {
        $search = ('/' == substr($search, 2, 1)) ? Carbon::parse('d/m/Y', $search) : $search;
        return $query->whereDate('date', '>=', $search);
    }

    /**
     * Activity log options.
     *
     * @return void
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable()
            ->logOnlyDirty();
    }

    /**
     * Get the patient that owns the diagnosis.
     *
     */
    public function patient()
    {
        return $this->belongsTo(Patient::class);
    }
}

app/Http/Controllers/DiagnosisController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreDiagnosisRequest;
use App\Http\Requests\UpdateDiagnosisRequest;
use App\Models\Diagnosis;
use App\Models\Patient;

class DiagnosisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function index(Patient $patient)
    {
        return view('diagnosis.index', compact('patient'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function create(Patient $patient)
    {
        return view('diagnosis.create', compact('patient'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreDiagnosisRequest  $request
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function store(StoreDiagnosisRequest $request, Patient $patient)
    {
        $data = $request->validated();

        $data['patient_id'] = $patient->id;

        $diagnosis = Diagnosis::create($data);

        session()->flash('flash.banner', __('Diagnosis has been created correctly.'));
        return redirect()->route('patients.diagnoses.show', [$patient->id, $diagnosis->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Patient  $patient
     * @param  \App\Models\Diagnosis  $diagnosis
     * @return \Illuminate\Http\Response
     */
    public function show(Patient $patient, Diagnosis $diagnosis)
    {
        return view('diagnosis.show', compact('diagnosis', 'patient'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Patient  $patient
     * @param  \App\Models\Diagnosis  $diagnosis
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient, Diagnosis $diagnosis)
    {
        return view('diagnosis.edit', compact('diagnosis', 'patient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateDiagnosisRequest  $request
     * @param  \App\Models\Patient  $patient
     * @param  \App\Models\Diagnosis  $diagnosis
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDiagnosisRequest $request, Patient $patient, Diagnosis $diagnosis)
    {
        $data = $request->validated();

        $diagnosis->update($data);

        session()->flash('flash.banner', __('Diagnosis has been edited successfully.'));
        return redirect()->route('patients.diagnoses.show', [$patient->id, $diagnosis->id]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/diagnosis/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('New Diagnosis') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <form method="post" action="{{ route('patients.diagnoses.store', $patient->id) }}">
                @csrf
                <div class="mt-10 sm:mt-0">
                    <div class="md:grid md:grid-cols-3 md:gap-6">
                        <div class="md:col-span-1">
                            <div class="px-4 sm:px-0">
                                <h3 class="text-lg font-medium leading-6 text-gray-900">{{ __('Diagnosis Information') }}</h3>
                            </div>
                        </div>
                        <div class="mt-5 md:mt-0 md:col-span-2">
                            <form action="#" method="POST">
                                <div class="shadow overflow-hidden sm:rounded-md">
                                    <div class="px-4 py-5 bg-white sm:p-6">
                                        <div class="grid grid-cols-6 gap-6">
                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="date" class="block text-sm font-medium text-gray-700">{{ __('Date') }}</label>
                                                <input type="text" name="date" id="date" value="{{ old('name', date('Y-m-d H:i')) }}" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" data-datetimepicker="datetime">
                                                @error('date')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="patient_id" class="block text-sm font-medium text-gray-700">{{ __('Patient') }}</label>
                                                <input type="text" id="patient_id" value="{{ $patient->full_name }}" disabled autocomplete="given-name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                            </div>

                                            <div class="col-span-6">
                                                <label for="description" class="block text-sm font-medium text-gray-700">{{ __('Description') }}</label>
                                                <textarea id="description" name="description" rows="20" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="{{ __('Diagnosis...') }} ">{{ old('description') }}</textarea>
                                                @error('description')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                        <button style="submit" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                            {{ __('Save') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/diagnosis/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Diagnosis') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <form method="post" action="{{ route('patients.diagnoses.update', [$patient->id, $diagnosis->id]) }}">
                @csrf
                @method('put')
                <div class="mt-10 sm:mt-0">
                    <div class="md:grid md:grid-cols-3 md:gap-6">
                        <div class="md:col-span-1">
                            <div class="px-4 sm:px-0">
                                <h3 class="text-lg font-medium leading-6 text-gray-900">{{ __('Diagnosis Information') }}</h3>
                            </div>
                        </div>
                        <div class="mt-5 md:mt-0 md:col-span-2">
                            <form action="#" method="POST">
                                <div class="shadow overflow-hidden sm:rounded-md">
                                    <div class="px-4 py-5 bg-white sm:p-6">
                                        <div class="grid grid-cols-6 gap-6">
                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="date" class="block text-sm font-medium text-gray-700">{{ __('Date') }}</label>
                                                <input type="text" name="date" id="date" value="{{ old('date', $diagnosis->date->format('Y-m-d H:i')) }}" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" data-datetimepicker="datetime">
                                                @error('date')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="patient_id" class="block text-sm font-medium text-gray-700">{{ __('Patient') }}</label>
                                                <input type="text" id="patient_id" value="{{ $patient->full_name }}" autocomplete="given-name" readonly class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                            </div>

                                            <div class="col-span-6">
                                                <label for="description" class="block text-sm font-medium text-gray-700">{{ __('Description') }}</label>
                                                <textarea id="description" name="description" rows="20" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="{{ __('Diagnosis...') }} ">{{ old('description', $diagnosis->description) }}</textarea>
                                                @error('description')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                        <button style="submit" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                            {{ __('Save') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/diagnosis/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Diagnoses List') }}
        </h2>
    </x-slot>

    <x-slot name="actions">
        <a href="{{ route('patients.diagnoses.create', $patient->id) }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition">{{ __('New diagnosis') }}</a>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">

                        <livewire:patient-diagnosis-table :patient="$patient" />

                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/diagnosis/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('View Diagnosis') }}
        </h2>
    </x-slot>

    <x-slot name="actions">
        <a href="{{ route('patients.diagnoses.edit', [$patient->id, $diagnosis->id]) }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition">{{ __('Edit Diagnosis') }}</a>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mt-10 sm:mt-0">
                <div class="md:grid md:grid-cols-3 md:gap-6">
                    <div class="md:col-span-1">
                        <div class="px-4 sm:px-0">
                            <h3 class="text-lg font-medium leading-6 text-gray-900">{{ __('Diagnosis Information') }}</h3>
                        </div>
                    </div>
                    <div class="mt-5 md:mt-0 md:col-span-2">
                        <form action="#" method="POST">
                            <div class="shadow overflow-hidden sm:rounded-md bg-gray-200">
                                <div class="px-4 py-5 bg-white sm:p-6">
                                    <div class="grid grid-cols-6 gap-6">
                                        <div class="col-span-6 sm:col-span-3">
                                            <label for="date" class="block text-sm font-medium text-gray-700">{{ __('Date') }}</label>
                                            <input type="text" name="date" id="date" value="{{ $diagnosis->date->isoFormat('L H:m') }}" readonly autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-3">
                                            <label for="dignosis[patient][full_name]" class="block text-sm font-medium text-gray-700">{{ __('Patient') }}</label>
                                            <input type="text" name="dignosis[patient][full_name]" id="dignosis[patient][full_name]" value="{{ $patient->full_name }}" readonly autocomplete="given-name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6">
                                            <label for="description" class="block text-sm font-medium text-gray-700">{{ __('Description') }}</label>
                                            <textarea id="description" name="description" readonly rows="20" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200" placeholder="{{ __('Diagnosis...') }} ">{{ $diagnosis->description }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>