routes/web.php
<?php

use App\Http\Controllers\DiagnosisController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    // Dashboard
    Route::get('/', fn () => view('dashboard'))->name('dashboard');

    // Patients
    Route::resource('/patients', PatientController::class)->except('destroy');
    Route::group([
        'prefix' => '/patients/{patient}',
        'as' => 'patients.',
    ], function () {
        // Diagnoses
        Route::resource('/diagnoses', DiagnosisController::class)->except('destroy');
    });

    Route::middleware('isAdmin')->group(function () {
        // Users
        Route::resource('/users', UserController::class)->except('destroy');
    });
});

app/Models/Patient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\LogOptions;
use Spatie\Activitylog\Traits\LogsActivity;
use Wildside\Userstamps\Userstamps;

class Patient extends Model
{
    use HasFactory, LogsActivity, SoftDeletes, Userstamps;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'surname',
        'id_card',
        'email',
        'phone',
        'address',
        'postcode',
        'city',
        'state',
        'country',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['full_name'];

    /**
     * Activity log options.
     *
     * @return void
     */
    public function getActivitylogOptions(): LogOptions
    {
        return LogOptions::defaults()
            ->logFillable()
            ->logOnlyDirty();
    }

    /**
     * Scope a query to only include patients of a given search.
     *
     * @param \Illuminate\Database\Eloquent\Builder  $query
     * @param string  $search
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSearch(Builder $query, string $search)
    {
        return $query->where(function ($query) use ($search) {
            $query->where('id_card', 'like', "%{$search}%")
                ->orWhereRaw("CONCAT_WS(' ', name, surname) like '%{$search}%'")
                ->orWhere('email', 'like', "%{$search}%")
                ->orWhere('phone', 'like', "%{$search}%")
                ->orWhere('city', 'like', "%{$search}%")
                ->orWhere('state', 'like', "%{$search}%");
        });
    }

    /**
     * Get the diagnoses with a role.
     *
     * @return void
     */
    public function diagnoses()
    {
        return $this->hasMany(Diagnosis::class);
    }

    /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        if (!empty($this->surname)) {
            return $this->name . ' ' . $this->surname;
        }

        return $this->name;
    }
}

app/Http/Controllers/PatientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePatientRequest;
use App\Http\Requests\UpdatePatientRequest;
use App\Models\Patient;

class PatientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('patient.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('patient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePatientRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePatientRequest $request)
    {
        $data = $request->validated();

        $patient = Patient::create($data);

        session()->flash('flash.banner', __('Patient has been created correctly.'));
        return redirect()->route('patients.show', $patient->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function show(Patient $patient)
    {
        return view('patient.show', compact('patient'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function edit(Patient $patient)
    {
        return view('patient.edit', compact('patient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePatientRequest  $request
     * @param  \App\Models\Patient  $patient
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePatientRequest $request, Patient $patient)
    {
        $data = $request->validated();

        $patient->update($data);

        session()->flash('flash.banner', __('Patient has been edited successfully.'));
        return redirect()->route('patients.show', $patient->id);
    }
}

app/Http/Livewire/PatientTable.php
<?php

namespace App\Http\Livewire;

use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use App\Models\Patient;
use Laravel\Jetstream\InteractsWithBanner;

class PatientTable extends DataTableComponent
{
    use InteractsWithBanner;

    /**
     * Indicates if the current user can select columns.
     *
     * @var boolean
     */
    public bool $columnSelect = true;

    /**
     * Remember the selection of columns.
     *
     * @var boolean
     */
    public bool $rememberColumnSelection = false;

    /**
     * Indicates if patient deletion is being confirmed.
     *
     * @var bool
     */
    public bool $confirmingDeletion = false;

    /**
     * The current model.
     *
     * @var \App\Models\Patient
     */
    public $model;

    /**
     * Current modal text.
     *
     * @var string
     */
    public $modalText;

    /**
     * The array defining the columns of the table.
     *
     * @return array
     */
    public function columns(): array
    {
        return [
            Column::make(__('Name'), 'full_name')
                ->selected()
                ->excludeFromSelectable(),
            Column::make(__('Email'), 'email')
                ->excludeFromSelectable(),
            Column::make(__('Phone'), 'phone')
                ->excludeFromSelectable(),
            Column::make(__('City'), 'city')
                ->excludeFromSelectable(),
            Column::make(__('Country'), 'country'),
            Column::blank()
                ->excludeFromSelectable(),
        ];
    }

    /**
     * The base query with search and filters for the table.
     *
     * @return Builder|Relation
     */
    public function query(): Builder
    {
        return Patient::query()
            ->when($this->getFilter('search'), fn ($query, $search) => $query->search($search));
    }

    /**
     * The view to render each row of the table.
     *
     * @return string
     */
    public function rowView(): string
    {
        return 'livewire.patient.table.rows';
    }

    /**
     * The view to add any modals for the table, could also be used for any non-visible html
     *
     * @return string
     */
    public function modalsView(): string
    {
        return 'livewire.components.modal.delete';
    }

    /**
     * Show delete modal.
     *
     * @param integer $id
     * @return void
     */
    public function confirmDeletion(int $id): void
    {
        $this->confirmingDeletion = true;
        $this->model = Patient::findOrFail($id);
        $this->modalText = $this->model->name;
    }

    /**
     * Reset delete modal.
     *
     * @return void
     */
    public function resetDeletion(): void
    {
        $this->reset('confirmingDeletion', 'modalText', 'model');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return void
     */
    public function delete(): void
    {
        $this->model->delete();
        $this->resetDeletion();
        $this->banner(__('The patient has been successfully deleted.'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/patient/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('New Patient') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <form method="post" action="{{ route('patients.store') }}">
                @csrf
                <div class="mt-10 sm:mt-0">
                    <div class="md:grid md:grid-cols-3 md:gap-6">
                        <div class="md:col-span-1">
                            <div class="px-4 sm:px-0">
                                <h3 class="text-lg font-medium leading-6 text-gray-900">{{ __('Patient Information') }}</h3>
                            </div>
                        </div>
                        <div class="mt-5 md:mt-0 md:col-span-2">
                            <form action="#" method="POST">
                                <div class="shadow overflow-hidden sm:rounded-md">
                                    <div class="px-4 py-5 bg-white sm:p-6">
                                        <div class="grid grid-cols-6 gap-6">
                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="name" class="block text-sm font-medium text-gray-700">{{ __('Name') }}</label>
                                                <input type="text" name="name" id="name" value="{{ old('name') }}" autocomplete="given-name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('name')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="surname" class="block text-sm font-medium text-gray-700">{{ __('Surname') }}</label>
                                                <input type="text" name="surname" id="surname" value="{{ old('surname') }}" autocomplete="family-name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('surname')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-2 lg:col-span-2">
                                                <label for="id_card" class="block text-sm font-medium text-gray-700">{{ __('ID card') }}</label>
                                                <input type="text" name="id_card" id="id_card" value="{{ old('id_card') }}" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('id_card')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-2 lg:col-span-2">
                                                <label for="phone" class="block text-sm font-medium text-gray-700">{{ __('Phone') }}</label>
                                                <input type="text" name="phone" id="phone" value="{{ old('phone') }}" autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('phone')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-4">
                                                <label for="email" class="block text-sm font-medium text-gray-700">{{ __('Email address') }}</label>
                                                <input type="text" name="email" id="email" value="{{ old('email') }}" autocomplete="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('email')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-3">
                                                <label for="country" class="block text-sm font-medium text-gray-700">{{ __('Country') }}</label>
                                                <input type="text" name="country" id="country" value="{{ old('country') }}" autocomplete="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('country')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6">
                                                <label for="address" class="block text-sm font-medium text-gray-700">{{ __('Street address') }}</label>
                                                <input type="text" name="address" id="address" value="{{ old('address') }}" autocomplete="address" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('address')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                                                <label for="city" class="block text-sm font-medium text-gray-700">{{ __('City') }}</label>
                                                <input type="text" name="city" id="city" autocomplete="city" value="{{ old('city') }}" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('city')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                                <label for="state" class="block text-sm font-medium text-gray-700">{{ __('State / Province') }}</label>
                                                <input type="text" name="state" id="state" value="{{ old('state') }}" autocomplete="state" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('state')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>

                                            <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                                <label for="postcode" class="block text-sm font-medium text-gray-700">{{ __('ZIP / Postal code') }}</label>
                                                <input type="text" name="postcode" id="postcode" value="{{ old('postcode') }}" autocomplete="postcode" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                                @error('postcode')
                                                    <p class="text-sm text-red-600">{{ $message }}</p>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                        <button style="submit" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                            {{ __('Save') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/patient/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Patients List') }}
        </h2>
    </x-slot>

    <x-slot name="actions">
        <a href="{{ route('patients.create') }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition">{{ __('New patient') }}</a>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">

                        <livewire:patient-table />

                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/patient/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('View Patient') }}
        </h2>
    </x-slot>

    <x-slot name="actions">
        <a href="{{ route('patients.diagnoses.index', $patient->id) }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition mr-3">{{ __('View Diagnoses') }}</a>
        <a href="{{ route('patients.edit', $patient->id) }}" class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring focus:ring-gray-300 disabled:opacity-25 transition">{{ __('Edit Patient') }}</a>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mt-10 sm:mt-0">
                <div class="md:grid md:grid-cols-3 md:gap-6">
                    <div class="md:col-span-1">
                        <div class="px-4 sm:px-0">
                            <h3 class="text-lg font-medium leading-6 text-gray-900">{{ __('Patient Information') }}</h3>
                        </div>
                    </div>
                    <div class="mt-5 md:mt-0 md:col-span-2">
                        <form action="#" method="POST">
                            <div class="shadow overflow-hidden sm:rounded-md bg-gray-200">
                                <div class="px-4 py-5 bg-white sm:p-6">
                                    <div class="grid grid-cols-6 gap-6">
                                        <div class="col-span-6 sm:col-span-3">
                                            <label for="name" class="block text-sm font-medium text-gray-700">{{ __('Name') }}</label>
                                            <input type="text" name="name" id="name" value="{{ $patient->name }}" readonly autocomplete="given-name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-3">
                                            <label for="surname" class="block text-sm font-medium text-gray-700">{{ __('Surname') }}</label>
                                            <input type="text" name="surname" id="surname" value="{{ $patient->surname }}" readonly autocomplete="family-name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-2 lg:col-span-2">
                                            <label for="id_card" class="block text-sm font-medium text-gray-700">{{ __('ID card') }}</label>
                                            <input type="text" name="id_card" id="id_card" value="{{ $patient->id_card }}" readonly autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-2 lg:col-span-2">
                                            <label for="phone" class="block text-sm font-medium text-gray-700">{{ __('Phone') }}</label>
                                            <input type="text" name="phone" id="phone" value="{{ $patient->phone }}" readonly autocomplete="off" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-4">
                                            <label for="email" class="block text-sm font-medium text-gray-700">{{ __('Email address') }}</label>
                                            <input type="text" name="email" id="email" value="{{ $patient->email }}" readonly autocomplete="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-3">
                                            <label for="country" class="block text-sm font-medium text-gray-700">{{ __('Country') }}</label>
                                            <input type="text" name="country" id="country" value="{{ $patient->country }}" readonly autocomplete="email" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6">
                                            <label for="address" class="block text-sm font-medium text-gray-700">{{ __('Street address') }}</label>
                                            <input type="text" name="address" id="address" value="{{ $patient->address }}" readonly autocomplete="address" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-6 lg:col-span-2">
                                            <label for="city" class="block text-sm font-medium text-gray-700">{{ __('City') }}</label>
                                            <input type="text" name="city" id="city" readonly autocomplete="city" value="{{ $patient->city }}" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                            <label for="state" class="block text-sm font-medium text-gray-700">{{ __('State / Province') }}</label>
                                            <input type="text" name="state" id="state" value="{{ $patient->state }}" readonly autocomplete="state" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>

                                        <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                            <label for="postcode" class="block text-sm font-medium text-gray-700">{{ __('ZIP / Postal code') }}</label>
                                            <input type="text" name="postcode" id="postcode" value="{{ $patient->postcode }}" readonly autocomplete="postcode" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md bg-gray-200">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>